from django.contrib import admin
from django.urls import path
from SmartCareApp import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.smartcare,name="smartcare"),
    path('logout/',views.logout,name="logout"),
    path('smartcare/',views.smartcare,name="smartcare"),
    path('callcentre/',views.callcentre,name="callcentre"),
    path('callregister/',views.callregister,name="callregister"),
    path('search/',views.search,name="search"),
    path('ordershow/<str:so>',views.ordershow,name="ordershow"),
    path('order/<str:lno>',views.order,name="order"),
    path('newcalls/',views.newcalls,name="newcalls"),
    path('freecalls/',views.freecalls,name="freecalls"),
    path('blankcalls/',views.blankcalls,name="blankcalls"),
    path('pendingcalls/',views.pendingcalls,name="pendingcalls"),
    path('servicecentre/',views.servicecentre,name="servicecentre"),
    path('callplanning/',views.callplanning,name="callplanning"),
    path('callupdate/',views.callupdate,name="callupdate"),
    # path('callupdateshow/',views.callupdateshow,name="callupdateshow"),
    path('vieworder/<str:so>',views.vieworder,name="vieworder"),
    path('appdetails/<str:lno>',views.appdetails,name="appdetails"),
    path('viewdetail/<str:loc>',views.viewdetail,name="viewdetail"),
    path('calldetailsave/<str:sno>',views.calldetailsave,name="calldetailsave"),
    path('orderdetailsave/',views.orderdetailsave,name="orderdetailsave"),
    path('callplan/',views.callplan,name="callplan"),
    path('viewplan/',views.viewplan,name="viewplan"),
    path('viewvisit/',views.viewvisit,name="viewvisit"),
    path('contract/',views.contract,name="contract"),
    path('contractsave/',views.contractsave,name="contractsave"),
    path('contractbook/',views.contractbook,name="contractbook"),
    path('visit/<str:so>',views.visit,name="visit"),
    path('visitsave/',views.visitsave,name="visitsave"),
    path('viewplanning/<str:sod>',views.viewplanning,name="viewplanning"),
    path('displayvisit/<str:sod>',views.displayvisit,name="displayvisit"),
    path('rating/',views.rating,name="rating"),
    path('feedback/',views.feedback,name="feedback"),
    path('royalty/<str:so>',views.royalty,name="royalty"),
    path('viewroyalty/<str:so>',views.viewroyalty,name="viewroyalty"),
    path('royaltysave/',views.royaltysave,name="royaltysave"),
    path('custdetail/',views.custdetail,name="custdetail"),
    path('custdetailsave/',views.custdetailsave,name="custdetailsave"),
    path('callclose/<str:so>',views.callclose,name="callclose"),
    path('plainsummery/',views.plainsummery,name="plainsummery"),
    path('reports/',views.reports,name="reports"),
    path('visitreport/',views.visitreport,name="visitreport"),

]
