# Generated by Django 2.2 on 2019-07-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Order', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=10)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Product', models.CharField(max_length=10)),
                ('Fault', models.CharField(max_length=10)),
                ('Mobile_No', models.CharField(max_length=10)),
                ('Pin_Code', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('Date', models.DateField()),
            ],
        ),
    ]
