# Generated by Django 2.2 on 2019-07-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0002_auto_20190719_0424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callcentre',
            old_name='Date',
            new_name='Reported_Date',
        ),
        migrations.AddField(
            model_name='callcentre',
            name='Reported_Time',
            field=models.CharField(default=1530, max_length=10),
            preserve_default=False,
        ),
    ]
