# Generated by Django 2.2 on 2019-07-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0003_auto_20190720_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcentre',
            name='Reported_Date',
            field=models.CharField(max_length=10),
        ),
    ]
