# Generated by Django 2.2 on 2019-07-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0004_auto_20190721_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Order', models.CharField(max_length=10)),
                ('Appointment_Date', models.CharField(max_length=30)),
                ('Appointment_Time', models.CharField(max_length=30)),
                ('Technician', models.CharField(max_length=10)),
                ('Technician_Name', models.CharField(max_length=50)),
                ('Execution_Date', models.CharField(max_length=10)),
                ('Execution_Time', models.CharField(default='', max_length=100)),
                ('End_Time', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
