# Generated by Django 2.2 on 2019-07-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0005_planning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Order', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=30)),
                ('Product', models.CharField(max_length=30)),
                ('Product_Code', models.CharField(max_length=10)),
                ('Serial_No', models.CharField(max_length=50)),
                ('DOP', models.CharField(max_length=10)),
                ('Expiry', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
