# Generated by Django 2.2 on 2019-07-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0007_details_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='Cust_Type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
