# Generated by Django 2.2 on 2019-07-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0008_details_cust_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='Contract',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='Effective_Date',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='Effective_Expiry',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
