# Generated by Django 2.2 on 2019-07-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0009_auto_20190727_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Code', models.CharField(max_length=30)),
                ('Mobile', models.CharField(max_length=30)),
            ],
        ),
    ]
