# Generated by Django 2.2 on 2019-07-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0010_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
