# Generated by Django 2.2 on 2019-07-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0011_auto_20190728_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=30)),
                ('Amount', models.CharField(max_length=30)),
            ],
        ),
    ]
