# Generated by Django 2.2 on 2019-07-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0012_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=30)),
                ('Contract_No', models.CharField(max_length=30)),
                ('Product_Code', models.CharField(max_length=10)),
                ('Serial_No', models.CharField(max_length=50)),
                ('Start_Date', models.CharField(max_length=100)),
                ('End_Expiry', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=30)),
            ],
        ),
    ]
