# Generated by Django 2.2 on 2019-07-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0013_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Contract',
            new_name='Contract_No',
        ),
    ]
