# Generated by Django 2.2 on 2019-07-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0014_auto_20190729_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='End_Expiry',
            new_name='End_Date',
        ),
    ]
