# Generated by Django 2.2 on 2019-08-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0016_visitdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Royalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Order', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=10)),
                ('Technician', models.CharField(max_length=30)),
                ('Service_Charge', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=10)),
                ('Part_Name', models.CharField(max_length=10)),
                ('Part_Amount', models.CharField(default='', max_length=10)),
                ('Total', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
