# Generated by Django 2.2 on 2019-08-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0017_royalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitdetail',
            name='Warranty',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='visitdetail',
            name='Work_Done',
            field=models.CharField(max_length=50),
        ),
    ]
