# Generated by Django 2.2 on 2019-08-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0018_auto_20190802_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Order', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=100)),
                ('Technician', models.CharField(max_length=30)),
                ('Technician_Name', models.CharField(max_length=50)),
                ('Product', models.CharField(max_length=10)),
                ('Work_Done', models.CharField(max_length=10)),
                ('Behaviour', models.CharField(default='', max_length=10)),
                ('Service', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
