# Generated by Django 2.2 on 2019-08-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0019_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Service_Order',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
