# Generated by Django 2.2 on 2019-08-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0020_auto_20190807_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=30)),
                ('Product', models.CharField(max_length=30)),
                ('Cust_Type', models.CharField(default='', max_length=30)),
                ('Product_Code', models.CharField(max_length=10)),
                ('Serial_No', models.CharField(max_length=50)),
                ('Bill_No', models.CharField(max_length=20)),
                ('DOP', models.CharField(max_length=10)),
                ('Expiry', models.CharField(default='', max_length=100)),
                ('Contract_No', models.CharField(default='-', max_length=100)),
                ('Effective_Date', models.CharField(default='-', max_length=100)),
                ('Effective_Expiry', models.CharField(default='-', max_length=100)),
            ],
        ),
    ]
