# Generated by Django 2.2 on 2019-08-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0021_location_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitdetail',
            name='UDate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visitdetail',
            name='UTime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
