# Generated by Django 2.2 on 2019-08-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0022_auto_20190807_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='royalty',
            old_name='Part_Amount',
            new_name='Category1',
        ),
        migrations.RemoveField(
            model_name='royalty',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='royalty',
            name='Part_Name',
        ),
        migrations.AddField(
            model_name='royalty',
            name='Category2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='royalty',
            name='Category3',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='royalty',
            name='Part_Amount1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='royalty',
            name='Part_Amount2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='royalty',
            name='Part_Amount3',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='royalty',
            name='Part_Name1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='royalty',
            name='Part_Name2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='royalty',
            name='Part_Name3',
            field=models.CharField(default='', max_length=10),
        ),
    ]
