# Generated by Django 2.2 on 2019-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0024_royalty_technician_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='royalty',
            name='RDate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='royalty',
            name='RTime',
            field=models.CharField(default='', max_length=50),
        ),
    ]
