# Generated by Django 3.0.3 on 2020-07-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCareApp', '0027_auto_20200716_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Work_Done',
            field=models.CharField(max_length=50),
        ),
    ]
